[phases.setup]
nixPkgs = ["python313", "gcc", "libxml2", "libxslt", "zlib"]

[phases.install]
cmds = [
    "pip install uv",
    "uv sync --no-dev --frozen",
]

[start]
cmd = "uv run uvicorn app.main:app --host 0.0.0.0 --port 8000"
